POST http://localhost:5000/post
content-type: application/json

{
    "id":"25",
    "name":"Rodolfpp"
}

###

PATCH  http://localhost:5000/patch
content-type:application/json

{
    "id":"1",
    "name":"rodolfa"
}


###
GET http://localhost:5000/
Content-Type: application/json

